name: Hello World Workflow

on:
  push:
    branches:
      - main  # Если твоя ветка называется master, напиши здесь master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hello Command
        run: make say-hello